// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// point_cell_matches_cpp
IntegerMatrix point_cell_matches_cpp(NumericMatrix points, NumericMatrix cells, double L, double cell_size);
RcppExport SEXP _swift_point_cell_matches_cpp(SEXP pointsSEXP, SEXP cellsSEXP, SEXP LSEXP, SEXP cell_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cells(cellsSEXP);
    Rcpp::traits::input_parameter< double >::type L(LSEXP);
    Rcpp::traits::input_parameter< double >::type cell_size(cell_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(point_cell_matches_cpp(points, cells, L, cell_size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_swift_point_cell_matches_cpp", (DL_FUNC) &_swift_point_cell_matches_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_swift(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
