#' Delete disk image of a `swift` environment
#'
#' @description
#' Deletes the files containing a global `swift` environment previously on the disk,
#' including associated particle data in subdirectories.
#'
#' @param stage Optional positive integer indicating the processing stage to remove. All higher stages are removed, too. If not given, all processing stages are removed.
#' @param filename Optional full path to the temporary file, without extension '.*.img'. If not provided, a simulation-specific default filename,
#' generated by \code{\link{swiftFileName}}, is adopted.
#' @param verbose Logical flag to enable timing and progress messages.
#'
#' @return None.
#'
#' @seealso \link{saveSwiftData}, \link{loadSwiftData}, \link{swiftFileName}
#'
#' @export

deleteSwiftData <- function(stage=NULL, filename=NULL, verbose=TRUE) {

  if (verbose) cooltools::tick('Remove post-processed data from disk')

  if (is.null(filename)) filename <- swiftFileName()

  # find all matching temporary files
  pattern = paste0(filename,'.*.img')
  files <- Sys.glob(pattern)
  if (length(files)==0) stop(sprintf('No files found with name: %s.*.img',filename))

  # extract vector of existing stage indices
  matches <- regmatches(files, regexec("\\.([0-9]+)\\.img$", files))
  integers <- as.integer(sapply(matches, `[`, 2))
  if (any(is.na(integers))) stop(sprintf('files %s with non-integer "*" found',pattern))

  # select stage indices to delete
  if (is.null(stage)) {
    stage = 1
    stages = integers
  } else {
    if (!(is.numeric(stage) && length(stage)==1 && stage==round(stage) && stage>0)) stop('if provided, stage must be a positive integer')
    stages = integers[integers>=stage]
  }

  nfiles = 0

  # remove particles
  if (!is.null(swift$particles$addedAfterStage)) {
    i = swift$particles$addedAfterStage+1
    if (i%in%stages) {
      fn = files[i]
      tmp_env <- new.env()
      load(fn, envir = tmp_env)
      if (!is.null(tmp_env$particles)) {
        all_names = names(tmp_env$particles)
        if (length(all_names)>0) {
          valid = grepl("^PartType\\d+$", all_names)
          if (any(valid)) {
            directory = paste0(swift$.paths$tmp,'particledata/')
            species_names = all_names[valid]
            for (field in species_names) {
              for (extension in c('.txt','.bin')) {
                fnpart = paste0(directory,tmp_env$particles[[field]]$filename,extension)
                if (file.exists(fnpart)) {
                  file.remove(fnpart)
                  nfiles = nfiles+1
                }
              }
            }
          }
        }
      }
    }
  }

  for (i in stages) {

    fn = files[i]

    # remove image file
    file.remove(fn)
    nfiles = nfiles+1

    # remove hash file
    fn.hash <- gsub('.img','.hash',fn)
    if (file.exists(fn.hash)) {
      file.remove(fn.hash)
      nfiles = nfiles+1
    }

  }

  clearSwift()

  if (verbose) cooltools::tock(sprintf('Deleted %d files for stages>=%d.',nfiles,stage))

  invisible(NULL)
}
