#' Load the `swift` environment from disk
#'
#' @importFrom cooltools tick tock
#' @importFrom bigmemory attach.big.matrix
#'
#' @description
#' Loads the global `swift` environment from a previously saved `.img` file on disk,
#' restoring all objects and internal state as they were at the time of saving.
#' This complements the function \code{\link{saveSwiftData}}. If the data on the image file
#' are identical to that currently in the `swift` environment, they are not reloaded.
#'
#' @param stage Optional positive integer indicating the processing stage. If not provided, the highest existing processing stage is loaded.
#' @param filename Optional full path to the temporary file, without extension '.*.img'. If not provided, a simulation-specific default filename,
#' generated by \code{\link{swiftFileName}}, is adopted.
#' @param verbose Logical flag to enable timing and progress messages.
#'
#' @return None. The stage of the loaded data is stored in `swift$backup$stage`
#'
#' @seealso \link{saveSwiftData}, \link{deleteSwiftData}, \link{swiftFileName}
#'
#' @export

loadSwiftData <- function(stage=NULL, filename=NULL, verbose=TRUE) {

  if (verbose) cooltools::tick('Access post-processed data')

  bindSwift(backup)

  if (is.null(filename)) filename <- swiftFileName()

  # find all matching temporary files
  pattern = paste0(filename,'.*.img')
  files <- Sys.glob(pattern)
  if (length(files)==0) {
    cooltools::tock('Not yet available.')
    backup = NULL
    return(invisible(NULL))
  }

  # extract vector of existing stage indices
  matches <- regmatches(files, regexec("\\.([0-9]+)\\.img$", files))
  integers <- as.integer(sapply(matches, `[`, 2))
  if (any(is.na(integers))) stop(sprintf('files %s with non-integer "*" found',pattern))

  # check vector of stage indices
  integers <- sort(integers[!is.na(integers)])
  if (any(integers!=seq_along(integers))) stop(sprintf('files %s do not form a contiguous list with *=1,2,3,...',pattern))

  # choose desired stage
  if (is.null(stage)) {
    stage=max(integers)
  } else {
    if (!(is.numeric(stage) && length(stage)==1 && stage==round(stage) && stage>0)) stop('if provided, stage must be a positive integer')
  }

  # make hash filename and load hash, if it exists
  fn.hash <- paste0(filename,'.',stage,'.hash')
  if (file.exists(fn.hash)) {
    hash = readLines(fn.hash) # loads `hash`
    if (!exists('hash')) stop('error with hash_file')
  } else {
    hash <- 0
  }

  # make hash of data currently in the RAM
  hash_current <- .hashEnvironment(swift,exclude='backup')

  if (hash_current == hash) {

    if (verbose) cooltools::tock(sprintf('RAM already up-to-date (stage %d).',stage))

  } else {

    # Clear existing data
    clearSwift(all.names=FALSE)

    # Load all saved variables into a temporary environment
    tmp_env <- new.env()
    fn.img <- paste0(filename,'.',stage,'.img')
    load(fn.img, envir = tmp_env)

    # Copy data into internal storage and (re)bind into swift
    for (name in ls(tmp_env, all.names = TRUE)) {
      if (name %in% .protected_names) {
        .internal_storage[[name]] <- tmp_env[[name]]
      } else {
        swift[[name]] <- tmp_env[[name]]
      }
    }

    # Reattach bigmemory data
    if (!is.null(swift$particles)) {
      all_containers = names(swift$particles)
      if (length(all_containers)>0) {
        if (!all(all_containers%in%c('halos','cells'))) stop('cannot yet deal with containers other than "halos" and "cells"')
        for (container in all_containers) {
          all_names = names(swift$particles[[container]])
          if (length(all_names)>0) {
            valid = grepl("^PartType\\d+$", all_names)
            if (any(valid)) {
              directory = paste0(swift$.paths$tmp,'particledata/')
              species_names = all_names[valid]
              for (field in species_names) {
                fn = paste0(directory,swift$particles[[container]][[field]]$filename,".txt")
                if (!file.exists(fn)) stop(sprintf('cannot find particle data file %s',fn))
                .internal_storage$particles[[container]][[field]]$data = bigmemory::attach.big.matrix(fn)
              }
            }
          }
        }
      }
    }

    backup = list(filename=filename,
                  stage=stage,
                  hash=hash_current)

    if (verbose) cooltools::tock(sprintf('Loaded from R-image (stage %d).',stage))

  }

  invisible(NULL)
}
