# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

point_cell_matches_cpp <- function(points, cells, L, cell_size = NA_real_) {
    .Call(`_swift_point_cell_matches_cpp`, points, cells, L, cell_size)
}

