#' Save the `swift` environment to disk
#'
#' @importFrom cooltools tick tock
#'
#' @description
#' Saves the global `swift` environment, except for objects with names beginning with '.',
#' such as the default object .paths, which is deliberately excluded to allow for
#' paths to change without requiring to recompute the data. The data are saved
#' in a file `[filename].img` using R's `save()` function, allowing reloading the entire
#' simulation context in a later session. An ascii file `[filename].hash` is also
#' produced which contains a hash for the `swift` environment to later assess
#' if the currently loaded data is identical to the saved one.
#'
#' @param stage Optional positive integer indicating the new processing stage. If not provided, this is set to `swift$stage+1`.
#' @param filename Optional full path to the temporary file, without extension '.*.img'. If not provided, a simulation-specific default filename,
#' generated by \code{\link{swiftFileName}}, is adopted.
#' @param force Logical flag. If TRUE, an R-image is saved even if the data hasn't changed since the last backup.
#' @param verbose Logical flag to enable timing and progress messages.
#'
#' @return None. Writes a `.img` file to disk containing the full `swift` environment, with pointers to linked particle data if available, as well as a `.hash` file containing a unique identifier of the img-file.
#'
#' @seealso \link{loadSwiftData}, \link{deleteSwiftData}, \link{swiftFileName}
#'
#' @export

saveSwiftData = function(stage=NULL, filename=NULL, verbose=TRUE, force=FALSE) {

  if (verbose) cooltools::tick('Save post-processed data as R-image')

  bindSwift(backup)

  # check hash
  hash = .hashEnvironment(swift, exclude='backup')
  if (!force && !is.null(backup$hash) && hash==backup$hash) {
    stop('trying to save unchanged data. Consider setting force=TRUE.')
  }

  # get filename
  if (is.null(filename)) filename = swiftFileName()
  backup$filename = filename

  # get stage
  if (is.null(stage)) {
    if (is.null(swift$backup$stage)) {
      stage = 1
    } else {
      stage = swift$backup$stage+1
    }
  } else {
    if (!(is.numeric(stage) && length(stage)==1 && stage==round(stage) && stage>0)) stop('if provided, stage must be a positive integer')
  }

  backup = list(filename=filename,
                stage=stage,
                hash=hash)

  save(list = ls(envir = swift, all.names = FALSE), envir = swift, file = paste0(filename,'.',stage,'.img'), compress = FALSE)

  writeLines(hash, paste0(filename,'.',stage,'.hash'))

  if (verbose) cooltools::tock(sprintf('Stage %d.',stage))

  invisible(NULL)

}
